### PR TITLE
Add 'links' for older timezone indicators.

### PR DESCRIPTION
**Pull request by erlandsona**
As described on the Wikipedia page here.
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

### CODE REVIEW

**Comment by justinmimbs** [comment]
Hi Austin, the data in `TimeZone.elm` is not updated manually, but it's generated by parsing the tz database. Take a look at `build.sh` and `build.py`, which do this.

**Comment by erlandsona** [comment]
Yeh but apparently the build script isn't capturing "links" in the output? 
I just installed the latest and our sister team in Kyiv ran into the fact that their machines are reporting "Europe/Kiev" not "Europe/Kyiv".

So the build scripts are missing the "linked" TZ's.

**Comment by erlandsona** [comment]
The list in this PR is represented by running this scrapper over the wikipedia above.
```js
links = Array(...document.querySelector('.wikitable tbody').querySelectorAll('tr')).flatMap(row => row.children[3].innerText.slice(0,4) === 'Link' ? [{from: row.children[1].innerText, to: Array(...row.children).slice(-1)[0].innerText.substring(8)}] : [])
```

**Comment by justinmimbs** [comment]
To support deprecated links, this library should build them from the `backward` file.

Just to be clear:
- This library builds its data directly from the [tz database](https://github.com/eggert/tz), not from Wikipedia. (The build for each release of this library replaces `TimeZone.elm` entirely.)
- This library **does** include links from the main tz data files.
- This library **does not** include links from the tz backward compatibility file.
- The name `Europe/Kiev` is deprecated, and [found only in the backward](https://github.com/eggert/tz/blob/45b28e68abdeb2cbf9da0a3853c0051f15f19492/backward#L314) file.

**Comment by erlandsona** [comment]
Ah okay, that sounds like what we ran into.
Closing as I assume this isn't "in scope" of the intended use case and I'm sure if someone else runs into it this  this issue should provide enough for them to decide how to proceed.

Thanks a ton!

**Pull request closed without merging**
